### ISSUE TITLE
no purple

### ISSUE THREAD

**Issue by Maki727** [Nigecat/obsidian-desmos#38] opened 2022-04-04 02:03 UTC
**Describe the bug**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Obsidian Version: [e.g. 0.13.33]
 - Plugin Version: [e.g. 0.5.2]

**Smartphone (please complete the following information):**
 - Obsidian Version: [e.g. 0.13.33]
 - Plugin Version: [e.g. 0.5.2]

**Additional context**

**Comment by Nigecat** [comment] 2022-04-04 06:45
(presumably) duplicate of #39

**Closed by Nigecat** 2022-04-04 06:45 UTC
Labels: bug
